# Generated by Django 4.2.9 on 2024-01-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=2, upload_to='Gallery'),
            preserve_default=False,
        ),
    ]
